### ISSUE TITLE
Installation step 4 seems to stay solving environment forever.

### ISSUE THREAD

**Issue by CFmicro** [nanoporetech/ont_tutorial_basicqc#10]
After following the readme step 4) to install the conda software dependencies
`conda env create --name BasicQC --file environment.yaml`
It stays `Solving environment:` forever with the cursor actively rotating.
the python3 process seems to be consuming a steady amount of CPU, indicating activity.

What should I do?

**Comment by zhanwen-cheng** [comment]
Hi CFmicro, I got the same issues as you when I was installing BasicQC with conda. Have you ever solved the problems?

**Comment by sagrudd** [comment]
Dear @CFmicro and @zhanwen-cheng 

Conda can occasionally get lost when building the map of dependencies to create the specified environment.

Mamba is a new conda installer that works pretty well. Please try replacing the `conda env create ... ` command with
1) `conda install -c conda-forge mamba`
2) `mamba env create --name BasicQC --file environment.yaml` 

The best recommendation here is to have a look at EPI2ME Labs (https://labs.epi2me.io) - we are moving all tutorials to EPI2ME Labs and the complete conda based environment is pre-installed in a docker container. The BasicQC tutorial is available through EPI2ME Labs (check out https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Basic_QC_Tutorial.ipynb ) and the environment is aimed to help you customise the reports that will facilitate your downstream bioinformatics explorations.

Good luck

**Comment by zhanwen-cheng** [comment]
Hi @sagrudd and @CFmicro , I have tried the Mamba you mentioned and it really worked well! However, for original "Conda solving" problem, I have it work through like this:
1. conda clean -a ----to clean the index cashe, lock file and so on~
2. change the environment.yaml file like this:
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - sagrudd
dependencies:
  - snakemake-minimal=5.2.4
  - python=3.6
  - r-essentials
  - r=3.5.1
  - r-base
  - rstudio
  - nanopore-r-basicqc
  - r-fastmatch
Specifically, as I am in China, so I changed the channels to tsinghua mirror. And I also delete the space before the '=', and it worked well. I am not sure whether this could help those who with the same issue. But I really recommend the 'mamba' as @sagrudd mentioned. It really helped me with this and other software installation environment.
Thanks~

**Comment by sagrudd** [comment]
That's awesome information, thanks @zhanwen-cheng - I'll make sure to let other bioinformaticians know about these conda mirrors in mainland China

**Comment by sagrudd** [comment]
I am closing this ticket - I think that Mamba is an appropriate solution for when Conda misbehaves.
