### ISSUE TITLE
barcoding_summary.txt from other demultiplexing tools ?

### ISSUE THREAD

**Issue by Francisjpll** [nanoporetech/ont_tutorial_basicqc#4]
Dear @Stephen Rudd,

First of all I would like to thank for these nice tutorials. Thank you so much for the efforts! 

And second of all, I just ran QC tutorial with my data which were basecalled with Guppy and demultiplexed with Porechop. 
I edited the **config.yaml`** leaving empty the barcodeFile and deleting demultiplexing part on the R code ( did I do right? Since I did not do demultiplexing with Guppy ).

I edited the **config.yaml **config.yaml`**  as follows :

inputFile:   "RawData/g2i0003_sequencing_summary.txt.bz2"
barcodeFile: 
basecaller:  "Guppy 2.3.7"
flowcellId:  "FAK41706"
tutorialText: FALSE

I am wondering if there is a barcoding summary txt from Porechop, Deepbinner: and also Epi2me fastq barcoding workflow to be able to analyze the demultiplexing part with this QC tutorial? if so, where exactly can I find those ?

I really appreciate your help.

Johanna

**Comment by sagrudd** [comment]
Dear Johanna @Francisjpll - thanks for the message and kind feedback!

It is correct to leave the `barcodeFile` field of the yaml file empty; there is however no need to edit the demultiplex components within the tutorial Rmd file - these barcode texts and figures will only be included if the barcodeFile can be found. The rest of your config.yaml looks good.

At the moment the tutorial can only present the barcode distributions from the Guppy demultiplex - I appreciate that Porechop, qcat and Deepbinner can also be appropriate solutions. I cannot comment as to how the barcode information could be best collated from these methods or if a suitable summary file is produced.

I will look into these requests, and possible solutions, when the BasicQC tutorial is updated - there are first a few new more tutorials to be released.

Thank you for your patience -
Stephen

**Comment by Francisjpll** [comment]
Well…Leaving the demultiplexing part on the R code (RDM file), I am getting the following error :

**Quitting from lines 641-661 (Nanopore_SumStatQC_Tutorial.Rmd)
Fehler in file.exists(config$barcodeFile) : ungültiges 'file' Argument
Ruft auf: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> file.exists**

I could not get an html report and I just got a folder named: Nanopore_SumStatQC_Tutotial_files with the PNG figures inside of  it.

How could I generate an html report in this situation without barcoding_summary file? 

When I removed the demultiplexing area on the R code, I could generate an html report (without the demultiplexing analysis). I do not know if this is right.

Thank you so much for your feedback!

Looking forward to hearing from you 

Best
Johanna

**Comment by sagrudd** [comment]
Hei Johanna - 
Line 648 of the tutorial RMD is the source of the error message here;
` if ("barcodeFile" %in% names(config) && file.exists(config$barcodeFile)) `

The empty barcodeFile entry in the yaml is propagated as a NULL and this generates the error in the `file.exists` query. I would therefore recommend that deleting the `barcodeFile :` line from config.yaml would be cleanest way to proceed - I'll update the documentation with this note ...

Thanks again for the feedback - 

Stephen
