### ISSUE TITLE
kable

### ISSUE THREAD

**Issue by amandawarr** [nanoporetech/ont_tutorial_basicqc#5]
Got an error about not finding kable

You're missing library(kableExtra)

**Comment by sagrudd** [comment]
Did you install the tutorial and accompanying files via the recommended conda route? This dependency is normally managed by conda.

**Comment by amandawarr** [comment]
I copied and pasted exactly what was in the tutorial. I wanted to test it before recommending it to others. I'm using Scientific Linux release 7.5 (Nitrogen).

I didn't notice any errors until I ran the R command, which was fixed by adding library(kableExtra). If I have time I will do it again from the beginning and see if I missed any errors during setup.

**Comment by sagrudd** [comment]
The best recommendation here is to have a look at EPI2ME Labs (https://labs.epi2me.io) - we are moving all tutorials to EPI2ME Labs and the complete conda based environment is pre-installed in a docker container. The BasicQC tutorial is available through EPI2ME Labs (check out https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Basic_QC_Tutorial.ipynb ) and the environment is aimed to help you customise the reports that will facilitate your downstream bioinformatics explorations.

Good luck
