### ISSUE TITLE
adapted code for Flongle layout

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/ont_tutorial_basicqc#7]
Hi,
Do you by chance have an edited version that would work with Flongle layout?
This version is expecting a different pore 2D pore layout and shows a wrong picture
Thanks

**Comment by sagrudd** [comment]
The best recommendation here is to have a look at EPI2ME Labs (https://labs.epi2me.io) - we are moving all tutorials to EPI2ME Labs and the complete conda based environment is pre-installed in a docker container. The BasicQC tutorial is available through EPI2ME Labs (check out https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Basic_QC_Tutorial.ipynb ) and the environment is aimed to help you customise the reports that will facilitate your downstream bioinformatics explorations. The new version of BasicQC includes flowcell layouts for both Flongle and PromethION.

Good luck
