### ISSUE TITLE
error during R slave markdown command

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/ont_tutorial_basicqc#8]
After running the Rmarkdown command I get the following error 

```
Error in match.arg(highlight, html_highlighters()) : 
  'arg' should be one of “default”, “tango”, “pygments”, “kate”, “monochrome”, “espresso”, “zenburn”, “haddock”, “breezedark”, “textmate”
Calls: <Anonymous> ... <Anonymous> -> pandoc_html_highlight_args -> match.arg
Execution halted

```

I can successfully run the R code in Rstudio but when trying markdown to either html or pdf I get error.

**Comment by sagrudd** [comment]
The best recommendation here is to have a look at EPI2ME Labs (https://labs.epi2me.io) - we are moving all tutorials to EPI2ME Labs and the complete conda based environment is pre-installed in a docker container. The BasicQC tutorial is available through EPI2ME Labs (check out https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Basic_QC_Tutorial.ipynb ) and the environment is aimed to help you customise the reports that will facilitate your downstream bioinformatics explorations.

Good luck
