### ISSUE TITLE
R --slave -e 'rmarkdown::render("Nanopore_SumStatQC_Tutorial.Rmd", "html_document")'

### ISSUE THREAD

**Issue by Sudosundu** [nanoporetech/ont_tutorial_basicqc#9]
Error while executing the command
R --slave -e 'rmarkdown::render("Nanopore_SumStatQC_Tutorial.Rmd", "html_document")'

Output:

Quitting from lines 80-112 (Nanopore_SumStatQC_Tutorial.Rmd) 
Error in data.table::fread(inputFile, stringsAsFactors = FALSE) : 
  File is empty: /tmp/RtmpaPksEA/file94b22ac06530
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> <Anonymous>

**Comment by sagrudd** [comment]
Can you share your config file and few 100s of lines from your sequencing summary file; we can have a look! 

The best recommendation here is to have a look at EPI2ME Labs (https://labs.epi2me.io) - we are moving all tutorials to EPI2ME Labs and the complete conda based environment is pre-installed in a docker container. The BasicQC tutorial is available through EPI2ME Labs (check out https://colab.research.google.com/github/epi2me-labs/tutorials/blob/master/Basic_QC_Tutorial.ipynb ) and the environment is aimed to help you customise the reports that will facilitate your downstream bioinformatics explorations.

Good luck
